### ISSUE TITLE
Feature request: Add optional party member buffs

### ISSUE THREAD

**Issue by jmunson** [rubensayshi/d3-ehp-calculator#10]
As a wizard, it would be nice to be able to see how my EHP goes up with various party buffs so I can see if they become worth it.

For example, the resist buff from both a warrior and a monk may make it so that Prismatic Energy Armor becomes worth it

**Comment by rubensayshi** [comment]
sounds like a good plan, very interested in how a monk helps me as a barb
too !

On Thu, May 31, 2012 at 3:28 PM, James Munson <
reply@reply.github.com

**Comment by rubensayshi** [comment]
I did get something working for this, but in the current state it requires to mess up the code of the tool a lot.
So I'm gonna focus on block / healing stuff first, after I got an initial version for that I will see if I change / cleanup the code so shared buffs can be implemented properly.

closing this ticket since its duplucate of #35 where the code changes are attached to
