### ISSUE TITLE
Time to live (TTL)

### ISSUE THREAD

**Issue by kiudee** [rubensayshi/d3-ehp-calculator#13]
As EHP do not take into account healing, a more helpful statistic would be _time to live_.
## What?

What it does is (assuming no dodges/blocks) asking:
How long will I be able to survive against a certain unmitigated incoming DPS
given my current mitigation and life + regen?
## Why?

Let's assume these two scenarios:
1. We have 10,000 Health and 90% mitigation. EHP = (10,000 \* (1 - 0.9)) = 100,000
2. We have 20,000 Health and 80% mitigation. EHP = (20,000 \* (1 - 0.8)) = 100,000

Now let's assume we have incoming damage of 10,000 / s. Without heals our TTL is now:
1. 10,000 / (10,000 \* (1 - 0.9) per second) = 10 s
2. 20,000 / (10,000 \* (1 - 0.8) per second) = 10 s

Still the same, but if we include heals (potions, skills) of 600 / s:
1. 10,000 / (10,000 \* (1 - 0.9) / s - 600 / s) = 25 s
2. 20,000 / (10,000 \* (1 - 0.8) / s - 600 / s) = 14 s

So we can see, that if we want to get a true picture of our survivability, we need to 
look at TTL instead of EHP.

Calculation is taken from http://www.reddit.com/r/Diablo3Strategy/comments/u86gt/monk_effective_health_is_not_the_beallendall_for/

**Comment by rubensayshi** [comment]
I agree and taking this step also goes hand in hand with calculating how good block is, if you'd split the 10000 dps taken up into 2 hits of 5000 taken / s for example :-)

Now I'd love to step up my game and do simulations like this but it has some pitfals:
1) we need a couple of senarios for incoming damage patterns (eg, 1 big pack of act1 mobs, act2 mobs, 1 or 2 boss fights).
2) we need a pattern of your healing, life per hit and how you press your buttons affect this a lot

**Comment by rubensayshi** [comment]
thinking about it, it really does make sence that TTL is what you're really interested in since TTL is what affects how much damage you can dish out and taking that you can figure out if your HP or the enemies HP runs out first xD

**Comment by Ucross** [comment]
This is the best EHP calculator there is.   However, since it does not do TTL it really fails at accurately predicting "survival" which I think is it's intended goal.

Right now, almost every class uses life gain to help survive and unfortunately this completely ignores it.   

I would LOVE to see this include TTL and if I can do anything to help please let me know.

**Comment by apathyduck** [comment]
I just found your calculator and wanted to say that I had been working on something similar that I have just been using myself, and wanted to share the way I was tackling this problem. Since dodge and block only trigger a percentage of the time I was calculating them using Bernoulli trials and outputting the distribution so you could see how much effective health you would gain X% of the time. This way you could compare apples to apples (converting dodge and block to expected effective health) when comparing an item with +dex to +vit along with your confidence interval. In my current version for dodge I was outputting hits to death, time to death, additional effective health from dodge, and total effective heath (which included damage reduction sources). Also, since the distribution is effected by monster damage I had inputs for monster damage and monster as. Of course for these numbers to be accurate a good estimation would be required, but for now I just left it up to the user to input these. I'm not all that familiar with javascript but if you want I can see if can tackle this. I could also just upload my C++ code and let someone else convert it.

EDIT: I apologize if I put this under the wrong section. Haven't used this site before (I'm an engineer not CS....).

**Comment by rubensayshi** [comment]
hey, I'd love to see code you've got so far since I still need to get a good start on this and having an working example would be awesome! you could mail me a tarbal or smt on ruben @ rubensayshi.com or create a github repo to place it in :-)

**Comment by apathyduck** [comment]
Sure, lemme do some work on it cause i left it in a weird state.

**Comment by mithrandi** [comment]
A simpler value to calculate than TTL is "ER" or effective regen; just as 100,000 EHP means that you can take a hit of 100,000 damage before any damage reduction / mitigation is applied, 100,000 ER/sec means that in one second, you regenerate the HP lost due to taking a hit of 100,000 damage. (As should be obvious, actual regen from pots / life regen / life on hit / etc. is "amplified" by damage reduction / mitigation in exactly the same way as total HP is amplified when considering EHP)

I think calculating ER on its own is the easy (or easier, anyway) part here, so it might make sense to implement that first; I thought this is what #29 is about, but after reading that, it doesn't seem to be. One of the comments on #29 references #36, but that issue seems completely unrelated, so maybe I'm just lost.

**Comment by rubensayshi** [comment]
should have mentioned #39 :D

which is what you just described ^_^

**Comment by mithrandi** [comment]
Aha! I looked for a similar issue but somehow missed that one, thanks.
