### ISSUE TITLE
Monster Damage

### ISSUE THREAD

**Issue by kdmcclel** [rubensayshi/d3-ehp-calculator#16]
Seek out a compiled list of monster damage per act and give an estimate of progression based on current EHP

**Comment by rubensayshi** [comment]
we also go #13 time to live 

this could be a decent alternative with a lot less work to it at first :-)

**Comment by kdmcclel** [comment]
Wouldn't we have to know incoming dps to do that.

Sent from my Windows Phone

**Comment by rubensayshi** [comment]
aye ^^

**Comment by rubensayshi** [comment]
you got any ideas how we could realize something like this?

**Comment by kdmcclel** [comment]
Brady games guide has the monster minimum damage per hit.
Normal/minion/champion/named per difficulty and what act they're in.

Sent from my Windows Phone

**Comment by rubensayshi** [comment]
hmm yea, but how would we decide on weither you got enough EHP to be on that level? 
It matters a lot on class for starters, but also on skill (player skill and skillbuild) ...

What we could do is ask people to tell their calculated EHP when they finished an act and use that to find the ranges of EHP that work for each act for each class ?

Tbh I kinda want to get something going which can value in block (since I think block can add a high amount of survivability, but its hard to theorycraft it by hand :D).
And if we're going that way it means we can also factor in health regen, life on hit and certain healing spells, see #13

I can get my hands on the guide (from a friend) if we cant find it online

**Comment by kdmcclel** [comment]
we don't have to suggest if you are good enough to play that act or
not. Just how long to can survive against x monster taking hits. I
don't think it needs to or can be completely precise. We need aps for
life on hit stat too.

Sent from my Windows Phone

**Comment by Ucross** [comment]
Players can insert their act/difficulty and then just supply them with an average low and high damage for that class.

E.g.    Player selects act III, hell difficulty:

Dmg/s:  Mnimial (a few mobs attacking you): 1000/s;  Moderate (a lot of mobs): 3000/s,  Heavy (elite packs): 9000/s

You could even let them select which type of dmg/s they want to see displayed to make the pages look cleaner.

Then, you factor in block, life gain, skills being used (this will be a big one but would be awesome), etc. etc. and show them TTL:    

TTL: 10s (light dmg: infinite, heavy damage 3s)
