### ISSUE TITLE
Check armor calculation

### ISSUE THREAD

**Issue by kdmcclel** [rubensayshi/d3-ehp-calculator#20]
"It calculates my buffed armor wrong, it says 10335.6 but I have 7458 (Barbarian)
Also pls change the sequence of input from VIT, DEX, INT, STR to STR, DEX, INT, VIT because that's the way they're shown ingame."

http://i.imgur.com/MMW6t.jpg

**Comment by rubensayshi** [comment]
fixed it, when you input a new character it didn't substract the armor you got from nerves of steel, as a result the simulated armor became higher then you initially inputed

**Comment by rubensayshi** [comment]
I just tried it with my own barb and it matches my ingame character, I'm
also pretty sure about the formulas I use.
What I'm not sure about is the interface, it makes people make mistakes a
lot; I need to work on that ;)

Try again with these steps:
1) goto manage characters (or open the calc and you're there as first page)
and create a new barba
2) login to your d3 character and check your character screen
3) type in the stats you see on your character screen at that moment into
the calculator
4) check which passives you have on already ingame (and check if you got
enchantress with you)
5) click 'create character'
6) now you should goto the next screen with all the EHP calculation stuff
here the armor field somewhere around the top should be a lower value then
what you input into it, since I substract the passives you already have on!
and around the bottom there's 'buffed armor' which should match

On Mon, Jun 11, 2012 at 9:14 PM, Aredian <
reply@reply.github.com
