### ISSUE TITLE
+1018 EHP for 10 Armor when I have (to say) 100.000 Armor?

### ISSUE THREAD

**Issue by CArnaboldi** [rubensayshi/d3-ehp-calculator#32]
Am I missing something? How is it possible that the tooltip beside armor says that, with already 100.000 armor (or 1.000.000, or more...) that if I get +10 Armor I always get +1018 EHP? Since the formula which gives amount of damage reduced for given armor and mlvl, fixing the mlvl, is an hyperbole:

A/(A+50*ml)

I would expect that with great amount of armor the contribution given adding even more armor in terms of EHP goes to 0. Am I missing something?

p.s. same thing applies for All Res, and probably for other sources of damage reduction, instead, dexterity reduces EHP added as intended...

**Comment by rubensayshi** [comment]
As in most games, armor (and resist in d3) indeed are a hyperbole if you look at the damage reduction, but it should (and will) always give the exact amount of EHP, because it scales with itself basicly, (apart from not being able to reach 100%) thats the reason why it's a hyperbole to begin with :-)

There was a good post on the diablofans forum about 'diminishing returns is a myth' but I can't seem to find it, it explained all this with some pretty charts :-)

**Comment by rubensayshi** [comment]
ah I found it, was on US forums: http://us.battle.net/d3/en/forum/topic/5149150485
