### ISSUE TITLE
Feature request: Button to equip new item on Item Compare

### ISSUE THREAD

**Issue by ninjeff** [rubensayshi/d3-ehp-calculator#34]
I just got some good use out of the Item Compare feature. Now that I am using the new item, it would be helpful if there was a button to replace the current item with the new item, to save some typing.

**Comment by rubensayshi** [comment]
hey, an awsome idea, specially because I had the same idea when I was building the itemcompare, however after an hour orso I removed that feature since it had some technical problems in the way I wanted to implement it :P

I will take another look at it however, since it's a good feature for returning users :D

**Comment by JustinPierce** [comment]
I was going to suggest this as well. It would also be nice if there were a one-click solution to clear the stats on the item you're comparing to in order to set up for a new comparison.

**Comment by smerchek** [comment]
@NinjaFish I've submitted a Pull Request for the 'Reset' functionality that you described in #51
