### ISSUE TITLE
Feature Request: Simple Calculations

### ISSUE THREAD

**Issue by jeremy-boschen** [rubensayshi/d3-ehp-calculator#37]
It would be really nice to be able to do simple calculations (+,-,*)in the character stat fields.

For example..

Vitality: 1125
Resists: 128

Let's say I want compare what reducing my vitality by X and increasing my resists by Y..

Vitality: 1125-100
Resists: 128+50

.. or I want to double my armor:
Armor: 2024*2

Doing this would allow me to tweak the fields so I can find what would be more effective, without having to reset them to my base stats each time.

**Comment by rubensayshi** [comment]
Since people are having trouble understanding the difference between the
first input screen and the second with the base stats I'm thinking about
adding a 're-input from characterscreen' step to it, locking the base stats
and adding another screen to 'play with stats' where you can give + or -
stats (maybe even with sliders).

On Thu, Jun 14, 2012 at 6:25 PM, Mutexed <
reply@reply.github.com

**Comment by jeremy-boschen** [comment]
You mean the item compare screen?

That works well for specific items, but it's a lot of input when I want to get a general idea of how to adjust my stats as a whole.

Not a big fan of a bunch of different screens either. I think it's great how so much is on one page where I can see everything at a glance. Sliders are nice, clicking a button 100 times doesn't sound too friendly :)

**Comment by ninjeff** [comment]
This suggestion would be handy for gems on the Item Compare screen, too. If I'm wearing a chest with vit and three amethysts of different qualities, it can be time-consuming and error-prone to add them all up.
