### ISSUE TITLE
+x% Chance to Block

### ISSUE THREAD

**Issue by mitchiru** [rubensayshi/d3-ehp-calculator#41]
This is a very important value I guess, and it is not mentioned. But as far as I know it works the same way as dodge (exept the fact that it doesn't trigger an revenge for barbs.)

**Comment by rubensayshi** [comment]
There's an open issue for this already #33 and I explained there that it unfortunatly works a bit different then dodge, check out this comment of mine: https://github.com/rubensayshi/d3-ehp-calculator/issues/33#issuecomment-6296691

Anyway it is highest priority for me to implement something to model block! Because I'm a shieldwielding barb too I understand that it's very important!

**Comment by mitchiru** [comment]
Explanation sounds rather accurately
