### ISSUE TITLE
block amount goes to 0 EHP when enchantress buff selected

### ISSUE THREAD

**Issue by morikal** [rubensayshi/d3-ehp-calculator#61]
When I enable the enchantress buff, the block amount EHP different goes to +0 EHP per 500 block amount.

When the enchantress buff is disabled, it shows something such as +13227 EHP for 500 block amount.

**Comment by rubensayshi** [comment]
hmm, i cant reproduce the problem, you mean the +ehp from the 'Average Block Amount' field right?

**Comment by morikal** [comment]
Screenshots:

http://img269.imageshack.us/img269/7504/53732458.jpg
http://img411.imageshack.us/img411/7668/66117798.jpg
http://img839.imageshack.us/img839/1338/93309351.jpg
http://img855.imageshack.us/img855/8438/12144389.jpg

**Comment by morikal** [comment]
When I recreate my character on another computer, this issue reproduced when I select all of:

Nerves of steel
War Cry - Impunity
and Enchantress buff

deselecting any of the 3 will make added block value once again show some EHP instead of 0.

It only seems to happen with 3 or more of the following enabled:
Nerves of Steel
Tough as Nails
War Cry - Impunity (but not other war crys)
Threatening Shout
Enchantress buff

Although War Cry (hardened wrath), War Cry (Impunity) and Nerves of steel triggers it too, but not
War Cry (hardened wrath), Nerves of Steel, and enchantress buff

Happy bug smashing :)

I took a quick glance at the code for 30 minutes or so, but I'm not familiar with JS (looks like an interesting language though). I was too lazy to delve into how
_.each(resulttypes, function(resulttype) ...
gets bindings for resulttypes and function(resulttype), since I didn't see those appear before that, and didn't really see them declared in other files... so anyway :)

PS: I really like this tool, and the code was really easy to follow, especially given that I have never looked at JS before. :). Keep up the good work.

**Comment by rubensayshi** [comment]
Okay, first of all, I'm really sorry that I didn't get back at you! I somehow forgot and didn't see the notification!

Second, I found what the problem is ... you have to much gear xD more block value really isn't doing anything for you :P

The incoming hit is set to 70k, you have enough damage reduction to reduce that hit already to below 5k, enough for your block value to completely cover it atm! If you would get more block value, it wouldn't be able to block more!
You can test this by setting the incoming hit value to 100k or higher ;-)
