### ISSUE TITLE
Armor seems to be wrong (Barb)

### ISSUE THREAD

**Issue by Disposition96** [rubensayshi/d3-ehp-calculator#64]
Every other stat I have once it shows buffed is right but armor is wrong by about 4k, what gives?

**Comment by rubensayshi** [comment]
Being 4k off most likely means you also made an error when inputting, but I can look into it properly if you supply me with the following information:

Ingame armor:
- without any (defensive) passives or buffs on, 
- with warcry (no rune), 
- with tough as nails (without warcry) 
- and finally with tough as nails and warcry (no rune)?

**also make sure you don't have the enchantress with you**

**Comment by Disposition96** [comment]
1. Without any (defensive) passives or buffs on - 4454
2. With warcry (no rune), - 5344
3. With tough as nails (without warcry) - 5567
4. With tough as nails and warcry (no rune) - 6458

Did some testing myself :
1. No skills, no enchantress : Armor before WC w/ no rune -  4454 /  Armor after WC - 5344 (Match)
2. Tough as Nails, no enchantress : Armor before WC w/ no rune - 5567 / Armor after WC - 6458 (Match)
3. Tough as Nails, enchantress : Armor before WC w/ no rune - 6235 / Armor after WC - 7125 (No Match - 9976 site)
4. TaN, Nerves of Steel, no Ench :  Armor before WC w/ no rune - 6836 / Armor after WC - 7930 (No match - 11383.95)
5. TaN, Nerves of Steel, Ench :  Armor before WC w/ no rune - 7656 / Armor after WC - 8750 (No match - 12561.6)

So I'm going to say it has something to do with both your Enchantress AND NoS formulas.

I can do other setups if you'd like but I hope this is enough data.  Also, your resistance formula works fine. :)

**Comment by Disposition96** [comment]
Also, you should come back to D3 so you can update item comparisons ect. :P

**Comment by rubensayshi** [comment]
Okay, your recorded stats from ingame seem to be correct and match the known amounts of bonus armor the skills should be giving, so that's not the problem.

However I'm not sure what you're doing on the calculator side of things, but with your base armor of 4454 and your VIT (somewhere around 1025 orso I think) I can enable all checkboxes and I will never get over 9853 armor ...  
Yet you manage to record 9976 at #3 on the website ...
Also the jump from #2 to #3 with enchantress is so weird since it doesn't match anything I can think of, while the difference between #4 and #5 seems to be correct ...

Can you check what the armor and vit values are in the boxes at the top, or maybe make a screenshot of it, I'm just interested in the top values ;) - I should have made an export or link to option :P

**Comment by Disposition96** [comment]
http://i1180.photobucket.com/albums/x412/dispo96/1sthalf_zps14d9abb1.png
http://i1180.photobucket.com/albums/x412/dispo96/1sthalff_zpsaa35c36b.png
http://i1180.photobucket.com/albums/x412/dispo96/2ndHalf_zps119489da.png
http://i1180.photobucket.com/albums/x412/dispo96/Buffed_zps751fac3d.png

**Comment by Disposition96** [comment]
All the info in screens.

**Comment by rubensayshi** [comment]
You said you had 4454 armor without any buffs / passives, but you have '6836' in the input box as base armor.  
I'm pretty sure 6836 is almost impossible to get unbuffed and if the base armor isn't correct then the formulas will never be.

**Comment by Disposition96** [comment]
Hot damn, go figure. :P
